minimum_prek_version = "0.3.8"
default_install_hook_types = ["pre-commit"]
default_stages = ["pre-commit"]

[[repos]]
repo = "local"
hooks = [
  { id = "ruff-format", name = "Ruff format", language = "system", entry = "uv run ruff format", files = "\\.pyi?$", priority = 0 },
  { id = "ruff-check", name = "Ruff check", language = "system", entry = "uv run ruff check --fix", files = "\\.pyi?$", priority = 10 },
  { id = "ty-check", name = "ty check", language = "system", entry = "uv run ty check", always_run = true, pass_filenames = false, priority = 20 },
]
